# Any changes here must also be made in _config_dev.yml

baseurl: "/core-1-interaction" # the subpath of your site, e.g. /blog
collections:
  lectures:
    output: true
future: true # allow posts dated in the future
title: "Core 1: Interaction" # the name of your site, e.g. ACME Corp.
url: "https://jackrieger.github.io" # the base hostname & protocol for your site, e.g. http://example.com
